# Forma 02 de implementar CrossOrigin - De manera global para que se aplique a todas las rutas de todos los microservicios
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - 'http://localhost:4200'
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE